### ISSUE TITLE
If you're looking to autogenerate wpilib bindings

### ISSUE THREAD

**Issue by virtuald** [qhdwight/frc-go#1]
The RobotPy project is starting to do that this year, you might be able to leverage some of that to make wrappers for go.

**Comment by qhdwight** [comment]
Yeah that would be awesome, but I'm not sure if I will get around to that. I looked a little in to auto-generated bindings but it gets quite messy since CGo does not work with C++ headers, only C headers. I have to create a special bridge file (see `frc/phoenix/include/phoenix.h`) so probably some custom code would have to be written.

**Comment by virtuald** [comment]
If you glance at what we did for `robotpy-ctre`, we autogenerated C++ classes around CTRE's C code, and then autogenerated python wrappers around those C++ classes. It's totally doable to autogenerate all the pieces.
